services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - '5678:5678'
    environment:
      # Configurações básicas
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https

      # Autenticação (ALTERE ESTAS CREDENCIAIS!)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=estrelinha1904

      # URL do webhook (será atualizada após deploy)
      - WEBHOOK_URL=https://seu-app-n8n.up.railway.app

        # Configurações de timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

      # Configurações de execução
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=info

      # Configuração para Railway
      - NODE_ENV=production

    volumes:
      - n8n_data:/home/node/.n8n

    # Healthcheck para manter o serviço ativo
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  n8n_data:
    driver: local
